### PR TITLE
Completed UI issues

### LINKED ISSUE #24: UI Issues
@vipul-goel Please check the following issues 

1.  Please use a [DateInput](https://neeto-ui.netlify.app/#/dateinput) from neetoUI inside of `New Note` or `Update Note` pane. You can use `Formik` to create a custom Formik validate `DateInput` component based on neetoUI.
2. The UI for the contacts page seems to be broken. Please center align the `Checkbox` component for `Add To Basecamp` column. 

Reference - 
image
3. In the `Contacts` Form, `Phone Number` needs to validate numbers. Currently, it accepts strings too. 
4. Please refer to [Text Overflow](https://tailwindcss.com/docs/text-overflow) from tailwindCSS and truncate the large texts based on a fixed width. 

Reference - 
image

### PR DESCRIPTION
**Pull request by vipul-goel**
Fixes #24

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Contacts/ContactsTable.jsx [hunk 1]
```diff
@@ -81,7 +81,7 @@ const ContactsTable = ({
               <td>{contact.email}</td>
               <td className="text-center">{contact.department}</td>
               <td className="text-center">{contact.contactNumber}</td>
-              <td>
+              <td className="contact-basecamp-checkbox">
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Contacts/ContactsTable.jsx:84]: Please use tailwind classnames here.

File: app/javascript/stylesheets/components/contact_table.scss [hunk 2]
```diff
@@ -0,0 +1,6 @@
+.contact-basecamp-checkbox {
+    .nui-input__wrapper {
+        display: flex;
+        justify-content: center;
+    }
+}
```
Comment (karthiknmenon) [inline app/javascript/stylesheets/components/contact_table.scss:6]: Please remove this and use tailwind classNames in the table.

File: app/javascript/stylesheets/application.scss [hunk 3]
```diff
@@ -6,3 +6,6 @@
 
 //Sidebar
 @import "./layouts/sidebar";
+
+//Contact table
+@import "./components//contact_table.scss"
```
Comment (karthiknmenon) [inline app/javascript/stylesheets/application.scss:11]: We wouldn't need this anymore since we will be switching to tailwind classnames.

Comment (karthiknmenon) [reply app/javascript/stylesheets/application.scss:11]: Also, while writing `scss` partials like you have in this case, please prefix the filename with `_` 
like - `components/_contact-table.scss`.
While importing the file, you can simply write - `components/contact-table`.

**Review by karthiknmenon — COMMENTED** [review]
@vipul-goel 
Please check the suggestions.
